MESSAGE_SEPARATOR = '\x1E'
MESSAGE_PART_SEPARATOR = '\x1F'

TOPIC_AUTH = 'A'
TOPIC_ERROR = 'X'
TOPIC_EVENT = 'E'
TOPIC_RECORD = 'R'
TOPIC_RPC = 'P'
TOPIC_WEBRTC = 'W'
TOPIC_PRIVATE = 'PRIVATE/'

ACTIONS_REQUEST = 'REQ'
ACTIONS_RESPONSE = 'RES'
ACTIONS_REJECTION = 'REJ'

ACTIONS_ACK = 'A'
